import Head from 'next/head'
import Image from 'next/image'
import Clock from '../components/Clock'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import NavLinks from '../components/NavLinks'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <NavLinks />
      <Footer />
    </div>
  )
}
