import Head from 'next/head'
import Container from '../components/Container'
import FeaturedPost from '../components/FeaturedPost'
import Footer from '../components/Footer'
import Layout from '../components/Layout'
import Navbar from '../components/Navbar'
import Posts from '../components/Posts'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FeaturedPost />
        <Posts />
      </Layout>
    </div>
  )
}
